### ISSUE TITLE
Pb installation Numahop

### ISSUE THREAD

**Issue by ragbx** [tech-advantage/numahop#42]
Bonjour,

J'essaie d'installer Numahop mais rencontre des erreurs. Pourriez-vous m'apporter votre aide s'il vous plaît ?
Je suis sur un serveur Debian 12, les prérequis sont remplis. Je vous mets en PJ les commandes exécutées et messages d'erreur rencontrés.

En vous remerciant.
[mon_install_erreurs.md](https://github.com/progilone/numahop/files/13536183/mon_install_erreurs.md)

**Comment by tixif** [comment]
Bonjour,

Je rencontre le même problème, pour le contourner je n'ai laissé que ça dans package.json :
"prettier:check": "prettier --check \"{,src/**/,webpack/}*.{css,scss}\"",
"prettier:format": "prettier --write \"{,src/**/,webpack/}*.{css,scss}\""

Ce n'est pas élégant mais ça permet d'avancer jusqu'au prochain problème...
seb
